export {default as menu} from "./menu.png"
export {default as Home } from "./home.png"
export {default as siren} from "./siren.png"
export {default as avtar} from "./avtar.jpeg"
export {default as search} from "./search.png"
export {default as medikit} from "./medikit.png"
export {default as Message} from "./massage.png"
export {default as Labtest} from "./lab_test.png"
export {default as question} from "./question.png"
export {default as medicine} from "./medicine.png"
export {default as Ambulance} from "./Ambulance.png"
export {default as notification} from "./notification.png"
export {default as profile} from "./profile.png"
export {default as self} from "./self.png"
export {default as onboard1} from "./onboard1.png"
export {default as onboard2} from "./onboard2.png"
export {default as onboard3} from "./onboard3.png"
export {default as UserDetailsScreenPNG} from "./UserDetailsScreenPNG.png"
export {default as AmbulanceBooking} from "./Ambulance-booking.png"
export {default as Hospitalanimation} from "./hospital-animation.gif"
export {default as ForgotPasswordScreenGif} from "./ForgotPassword.gif"
export {default as mail} from "./mail.gif"
export {default as paymentdone} from "./paymentdone.gif"

export {default as RegisterScreenGIF} from "./RegistrationPage.gif"
export {default as baby} from "./baby.jpeg"
export {default as digest} from "./digest.png"
export {default as doctor} from "./doctor.jpeg"
export {default as hair} from "./hair.jpeg"
export {default as plus_sign} from "./plus_sign.jpeg"
export {default as pregnant} from "./pregnant.png"
export {default as sexio} from "./sexio.jpeg"
export {default as stethscope} from "./stethscope.png"
export {default as teeth} from "./teeth.jpeg"
export {default as smallpox_person} from "./smallpox_person.png"
export {default as itching_person} from "./itching_person.png"
export {default as finger_cut} from "./finger_cut.png"

