import { StyleSheet } from "react-native";

const style = StyleSheet.create({
    container:{
        flex:1,
        //justifyContent:'center',
        alignItems:'center',
    },
    topBackTouchable:{
        position:'absolute',
        top:10,
        left:20,
        //elevation:10,
        borderRadius:30,
        //shadowColor:'#148CD0',
    },
    topBackTouchableText:{
        marginTop:15,
        fontSize:20,
        color:'blue',
      },
    topHeadingText:{
        marginTop:15,
        fontWeight:'bold',
        fontSize:25,
    },
    topUserImage:{
        marginTop:20,
        width:110,
        height:110,
        borderRadius: 55,
    },
    mainDetailsContainer:{
        flex:1,
        width:'100%',
        //backgroundColor:'grey',
    },
    detailNameText:{
        marginTop:15,
        marginLeft:15,
        //fontWeight:'bold',
        fontSize:20,
    },
    detailValueText:{
        marginTop:15,
        marginLeft:15,
        fontWeight:'bold',
        fontSize:20,
        backgroundColor:'#DDE0FF',
        width:'93%',
        borderBottomColor:'grey',
        borderBottomWidth:1,
        padding:8,
        borderRadius:10,
    },
    inputValues:{
        marginTop:15,
        marginLeft:15,
        backgroundColor:'#DDE0FF',
        width:'93%',
        borderBottomColor:'grey',
        borderBottomWidth:1,
        padding:8,
        borderRadius:10,
    },
    itemPicker:{
        backgroundColor:'#DDE0FF',
        width:'93%',
        height:48,
        marginTop:15,
        marginLeft:'3.5%',
        borderRadius:10,
        borderBottomColor:'grey',
        borderBottomWidth:1,
    },
    bottomInfoUpdateTouchable:{
        backgroundColor:'#148CD0',
        width:'100%',
        height:50,
        alignItems:'center',
        justifyContent:'center',
    },
    bottomInfoUpdateTouchableText:{
        fontWeight:'bold',
        fontSize:25,
        color:'white',
    },
})

export {style};